### ISSUE TITLE
The type 'LocalConfigStore' already contains a definition for 'Id'

### ISSUE THREAD

**Issue by Dremor** [delegateas/XrmContext#4]
After generating the file with XrmContext (1.4.2), I'm unable to build the code because of the following error: 

`Error	CS0102	The type 'LocalConfigStore' already contains a definition for 'Id'	`

Associated warning :
`Warning	CS0114	'LocalConfigStore.Id' hides inherited member 'Entity.Id'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword.`

Best regards,

Dremor

**Comment by TomMalow** [comment]
My guess is that you have not defined a solutions that XrmContext should generate the context from. 

XrmContext tries to generate context for all entites in CRM including system entites. However, XrmContext does not currently support all system entites, in this case the localconfigstore entity. My suggestion is to define a solution that contains the entities you want to work with. This is also best practice as this also reduces the generated context file size. See the [argument list](https://github.com/delegateas/XrmContext/wiki/Tool-usage) for how to define solutions to build the context from.

The more technical reason for this error is that we add an additional field in context called `Id` for each entity in order to generalise them a bit. So the Account entity has the field `AccountId` and we add `id` that points to `AccountId.` In this case the LocalConfigStore id-field is already called `id` which means that we can't add a new field with the same name.

**Comment by henrikhannemose** [comment]
I agree that it makes sense to specify which CRM-solution you are working with when generating the context. Refer to https://github.com/delegateas/XrmContext/issues/5 for a suggestion of making specifying  a solution mandatory.

**Comment by Dremor** [comment]
Indeed. but in some case, generating the whole context can be useful. Could it be possible to add a blacklist for the entities that XrmContext doesn't support (yet) ?
